# Exploração SIDRA

Extrações municipais com variáveis, unidades e classificações explícitas. Totais não são somados às suas categorias. Dados especiais são interpretados pelo pipeline; percentuais precisam fechar 100% em cada dimensão.

In [1]:
from pathlib import Path
import sys
PROJECT_ROOT = next(p for p in (Path.cwd(), *Path.cwd().parents)
                    if (p / "utils/analysis_pipeline.py").exists())
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
import polars as pl
from IPython.display import display

from utils.analysis_pipeline import build_ibge_outputs
ibge = build_ibge_outputs()
for name, frame in ibge.items():
    print(name, frame.shape)
    display(frame.head(10))

populacao (116984, 5)

shape: (10, 5)
┌──────┬──────────────────┬────────────────────────────┬───────────┬─────────────────────────┐
│ ano  ┆ codigo_municipio ┆ municipio                  ┆ populacao ┆ fonte_populacao         │
│ ---  ┆ ---              ┆ ---                        ┆ ---       ┆ ---                     │
│ i32  ┆ str              ┆ str                        ┆ u64       ┆ str                     │
╞══════╪══════════════════╪════════════════════════════╪═══════════╪═════════════════════════╡
│ 2001 ┆ 110001           ┆ Alta Floresta D'Oeste - RO ┆ 26919     ┆ SIDRA 6579 - estimativa │
│      ┆                  ┆                            ┆           ┆ popula…                 │
│ 2001 ┆ 110002           ┆ Ariquemes - RO             ┆ 76371     ┆ SIDRA 6579 - estimativa │
│      ┆                  ┆                            ┆           ┆ popula…                 │
│ 2001 ┆ 110003           ┆ Cabixi - RO                ┆ 7501      ┆ SIDRA 6579 - estimativa │
│      ┆                  ┆                            ┆           ┆ popula…                 │
│ 2001 ┆ 110004           ┆ Cacoal - RO                ┆ 73996     ┆ SIDRA 6579 - estimativa │
│      ┆                  ┆                            ┆           ┆ popula…                 │
│ 2001 ┆ 110005           ┆ Cerejeiras - RO            ┆ 18012     ┆ SIDRA 6579 - estimativa │
│      ┆                  ┆                            ┆           ┆ popula…                 │
│ 2001 ┆ 110006           ┆ Colorado do Oeste - RO     ┆ 21421     ┆ SIDRA 6579 - estimativa │
│      ┆                  ┆                            ┆           ┆ popula…                 │
│ 2001 ┆ 110007           ┆ Corumbiara - RO            ┆ 10290     ┆ SIDRA 6579 - estimativa │
│      ┆                  ┆                            ┆           ┆ popula…                 │
│ 2001 ┆ 110008           ┆ Costa Marques - RO         ┆ 10679     ┆ SIDRA 6579 - estimativa │
│      ┆                  ┆                            ┆           ┆ popula…                 │
│ 2001 ┆ 110009           ┆ Espigão D'Oeste - RO       ┆ 25985     ┆ SIDRA 6579 - estimativa │
│      ┆                  ┆                            ┆           ┆ popula…                 │
│ 2001 ┆ 110010           ┆ Guajará-Mirim - RO         ┆ 38679     ┆ SIDRA 6579 - estimativa │
│      ┆                  ┆                            ┆           ┆ popula…                 │
└──────┴──────────────────┴────────────────────────────┴───────────┴─────────────────────────┘

saneamento_2010 (5565, 20)

shape: (10, 20)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ ano  ┆ codigo_mun ┆ municipio  ┆ pct_agua_o ┆ … ┆ pct_sem_ba ┆ pct_lixo_ ┆ pct_lixo_ ┆ pct_lixo_ │
│ ---  ┆ icipio     ┆ ---        ┆ utra_forma ┆   ┆ nheiro_ou_ ┆ cacamba_s ┆ outro_des ┆ servico_l │
│ i32  ┆ ---        ┆ str        ┆ ---        ┆   ┆ sanitario  ┆ ervico_li ┆ tino      ┆ impeza    │
│      ┆ str        ┆            ┆ f64        ┆   ┆ ---        ┆ mpe…      ┆ ---       ┆ ---       │
│      ┆            ┆            ┆            ┆   ┆ f64        ┆ ---       ┆ f64       ┆ f64       │
│      ┆            ┆            ┆            ┆   ┆            ┆ f64       ┆           ┆           │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2010 ┆ 110001     ┆ Alta       ┆ 0.08       ┆ … ┆ 3.51       ┆ 4.48      ┆ 43.14     ┆ 52.38     │
│      ┆            ┆ Floresta   ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ D'Oeste -  ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ RO         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2010 ┆ 110002     ┆ Ariquemes  ┆ 0.13       ┆ … ┆ 0.64       ┆ 2.85      ┆ 14.86     ┆ 82.29     │
│      ┆            ┆ - RO       ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2010 ┆ 110003     ┆ Cabixi -   ┆ 0.3        ┆ … ┆ 0.76       ┆ 0.15      ┆ 50.23     ┆ 49.62     │
│      ┆            ┆ RO         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2010 ┆ 110004     ┆ Cacoal -   ┆ 0.14       ┆ … ┆ 0.89       ┆ 8.96      ┆ 21.06     ┆ 69.98     │
│      ┆            ┆ RO         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2010 ┆ 110005     ┆ Cerejeiras ┆ 0.07       ┆ … ┆ 0.5        ┆ 0.19      ┆ 21.65     ┆ 78.16     │
│      ┆            ┆ - RO       ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2010 ┆ 110006     ┆ Colorado   ┆ 0.37       ┆ … ┆ 0.82       ┆ 13.73     ┆ 30.89     ┆ 55.38     │
│      ┆            ┆ do Oeste - ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ RO         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2010 ┆ 110007     ┆ Corumbiara ┆ 0.11       ┆ … ┆ 2.72       ┆ 8.42      ┆ 62.17     ┆ 29.41     │
│      ┆            ┆ - RO       ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2010 ┆ 110008     ┆ Costa      ┆ 0.16       ┆ … ┆ 2.27       ┆ 11.96     ┆ 44.26     ┆ 43.78     │
│      ┆            ┆ Marques -  ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ RO         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2010 ┆ 110009     ┆ Espigão    ┆ 0.25       ┆ … ┆ 1.12       ┆ 8.44      ┆ 33.57     ┆ 57.99     │
│      ┆            ┆ D'Oeste -  ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ RO         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2010 ┆ 110010     ┆ Guajará-Mi ┆ 0.4        ┆ … ┆ 2.3        ┆ 14.37     ┆ 20.45     ┆ 65.18     │
│      ┆            ┆ rim - RO   ┆            ┆   ┆            ┆           ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

saneamento_2010_longo (94605, 6)

shape: (10, 6)
┌──────┬──────────────────┬─────────────────────────┬─────────────┬────────────────────────┬───────┐
│ ano  ┆ codigo_municipio ┆ municipio               ┆ dimensao    ┆ indicador              ┆ valor │
│ ---  ┆ ---              ┆ ---                     ┆ ---         ┆ ---                    ┆ ---   │
│ i32  ┆ str              ┆ str                     ┆ str         ┆ str                    ┆ f64   │
╞══════╪══════════════════╪═════════════════════════╪═════════════╪════════════════════════╪═══════╡
│ 2010 ┆ 110001           ┆ Alta Floresta D'Oeste - ┆ agua        ┆ pct_agua_outra_forma   ┆ 0.08  │
│      ┆                  ┆ RO                      ┆             ┆                        ┆       │
│ 2010 ┆ 110001           ┆ Alta Floresta D'Oeste - ┆ agua        ┆ pct_agua_poco_nascente ┆ 0.58  │
│      ┆                  ┆ RO                      ┆             ┆ _aldeia                ┆       │
│ 2010 ┆ 110001           ┆ Alta Floresta D'Oeste - ┆ agua        ┆ pct_agua_poco_nascente ┆ 0.0   │
│      ┆                  ┆ RO                      ┆             ┆ _fora_al…              ┆       │
│ 2010 ┆ 110001           ┆ Alta Floresta D'Oeste - ┆ agua        ┆ pct_agua_poco_nascente ┆ 5.27  │
│      ┆                  ┆ RO                      ┆             ┆ _fora_pr…              ┆       │
│ 2010 ┆ 110001           ┆ Alta Floresta D'Oeste - ┆ agua        ┆ pct_agua_poco_nascente ┆ 69.28 │
│      ┆                  ┆ RO                      ┆             ┆ _proprie…              ┆       │
│ 2010 ┆ 110001           ┆ Alta Floresta D'Oeste - ┆ agua        ┆ pct_agua_rede_geral    ┆ 24.4  │
│      ┆                  ┆ RO                      ┆             ┆                        ┆       │
│ 2010 ┆ 110001           ┆ Alta Floresta D'Oeste - ┆ agua        ┆ pct_agua_rio_acude_lag ┆ 0.39  │
│      ┆                  ┆ RO                      ┆             ┆ o_igarap…              ┆       │
│ 2010 ┆ 110001           ┆ Alta Floresta D'Oeste - ┆ energia     ┆ pct_com_energia_eletri ┆ 94.75 │
│      ┆                  ┆ RO                      ┆             ┆ ca                     ┆       │
│ 2010 ┆ 110001           ┆ Alta Floresta D'Oeste - ┆ energia     ┆ pct_sem_energia_eletri ┆ 5.25  │
│      ┆                  ┆ RO                      ┆             ┆ ca                     ┆       │
│ 2010 ┆ 110001           ┆ Alta Floresta D'Oeste - ┆ esgotamento ┆ pct_banheiro_exclusivo ┆ 84.99 │
│      ┆                  ┆ RO                      ┆             ┆ _outro_e…              ┆       │
└──────┴──────────────────┴─────────────────────────┴─────────────┴────────────────────────┴───────┘

saneamento_2022 (5570, 32)

shape: (10, 32)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ ano  ┆ codigo_mun ┆ municipio  ┆ pct_agua_l ┆ … ┆ pct_lixo_e ┆ pct_lixo_ ┆ pct_lixo_ ┆ pct_lixo_ │
│ ---  ┆ icipio     ┆ ---        ┆ igada_rede ┆   ┆ nterrado_p ┆ outro_des ┆ queimado_ ┆ terreno_e │
│ i32  ┆ ---        ┆ str        ┆ _carro_pip ┆   ┆ ropriedade ┆ tino      ┆ proprieda ┆ ncosta_ar │
│      ┆ str        ┆            ┆ …          ┆   ┆ ---        ┆ ---       ┆ de        ┆ ea_…      │
│      ┆            ┆            ┆ ---        ┆   ┆ f64        ┆ f64       ┆ ---       ┆ ---       │
│      ┆            ┆            ┆ f64        ┆   ┆            ┆           ┆ f64       ┆ f64       │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2022 ┆ 110001     ┆ Alta       ┆ 0.0        ┆ … ┆ 2.46       ┆ 0.66      ┆ 35.13     ┆ 0.27      │
│      ┆            ┆ Floresta   ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ D'Oeste -  ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ RO         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2022 ┆ 110002     ┆ Ariquemes  ┆ 0.0        ┆ … ┆ 0.83       ┆ 0.47      ┆ 8.26      ┆ 0.02      │
│      ┆            ┆ - RO       ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2022 ┆ 110003     ┆ Cabixi -   ┆ 0.0        ┆ … ┆ 3.05       ┆ 1.32      ┆ 34.52     ┆ 0.05      │
│      ┆            ┆ RO         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2022 ┆ 110004     ┆ Cacoal -   ┆ 0.0        ┆ … ┆ 0.77       ┆ 0.36      ┆ 13.15     ┆ 0.06      │
│      ┆            ┆ RO         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2022 ┆ 110005     ┆ Cerejeiras ┆ 0.0        ┆ … ┆ 1.86       ┆ 1.04      ┆ 10.06     ┆ 0.0       │
│      ┆            ┆ - RO       ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2022 ┆ 110006     ┆ Colorado   ┆ 0.0        ┆ … ┆ 0.85       ┆ 0.45      ┆ 21.2      ┆ 0.25      │
│      ┆            ┆ do Oeste - ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ RO         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2022 ┆ 110007     ┆ Corumbiara ┆ 0.0        ┆ … ┆ 7.25       ┆ 0.63      ┆ 43.77     ┆ 0.46      │
│      ┆            ┆ - RO       ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2022 ┆ 110008     ┆ Costa      ┆ 0.0        ┆ … ┆ 2.36       ┆ 1.39      ┆ 32.08     ┆ 0.6       │
│      ┆            ┆ Marques -  ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ RO         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2022 ┆ 110009     ┆ Espigão    ┆ 0.0        ┆ … ┆ 1.59       ┆ 0.67      ┆ 21.81     ┆ 1.65      │
│      ┆            ┆ D'Oeste -  ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ RO         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2022 ┆ 110010     ┆ Guajará-Mi ┆ 0.0        ┆ … ┆ 0.67       ┆ 0.59      ┆ 19.88     ┆ 0.72      │
│      ┆            ┆ rim - RO   ┆            ┆   ┆            ┆           ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

saneamento_2022_longo (161530, 7)

shape: (10, 7)
┌──────┬──────────────────┬───────────────┬──────────────┬──────────┬──────────────────────┬───────┐
│ ano  ┆ codigo_municipio ┆ municipio     ┆ tabela_sidra ┆ dimensao ┆ indicador            ┆ valor │
│ ---  ┆ ---              ┆ ---           ┆ ---          ┆ ---      ┆ ---                  ┆ ---   │
│ i32  ┆ str              ┆ str           ┆ i32          ┆ str      ┆ str                  ┆ f64   │
╞══════╪══════════════════╪═══════════════╪══════════════╪══════════╪══════════════════════╪═══════╡
│ 2022 ┆ 110001           ┆ Alta Floresta ┆ 6803         ┆ agua     ┆ pct_agua_ligada_rede ┆ 0.0   │
│      ┆                  ┆ D'Oeste - RO  ┆              ┆          ┆ _carro_pip…          ┆       │
│ 2022 ┆ 110001           ┆ Alta Floresta ┆ 6803         ┆ agua     ┆ pct_agua_ligada_rede ┆ 0.0   │
│      ┆                  ┆ D'Oeste - RO  ┆              ┆          ┆ _chuva_pri…          ┆       │
│ 2022 ┆ 110001           ┆ Alta Floresta ┆ 6803         ┆ agua     ┆ pct_agua_ligada_rede ┆ 0.09  │
│      ┆                  ┆ D'Oeste - RO  ┆              ┆          ┆ _nascente_…          ┆       │
│ 2022 ┆ 110001           ┆ Alta Floresta ┆ 6803         ┆ agua     ┆ pct_agua_ligada_rede ┆ 0.0   │
│      ┆                  ┆ D'Oeste - RO  ┆              ┆          ┆ _outra_pri…          ┆       │
│ 2022 ┆ 110001           ┆ Alta Floresta ┆ 6803         ┆ agua     ┆ pct_agua_ligada_rede ┆ 2.79  │
│      ┆                  ┆ D'Oeste - RO  ┆              ┆          ┆ _poco_prof…          ┆       │
│ 2022 ┆ 110001           ┆ Alta Floresta ┆ 6803         ┆ agua     ┆ pct_agua_ligada_rede ┆ 4.31  │
│      ┆                  ┆ D'Oeste - RO  ┆              ┆          ┆ _poco_raso…          ┆       │
│ 2022 ┆ 110001           ┆ Alta Floresta ┆ 6803         ┆ agua     ┆ pct_agua_ligada_rede ┆ 0.05  │
│      ┆                  ┆ D'Oeste - RO  ┆              ┆          ┆ _superfici…          ┆       │
│ 2022 ┆ 110001           ┆ Alta Floresta ┆ 6803         ┆ agua     ┆ pct_agua_rede_geral_ ┆ 26.48 │
│      ┆                  ┆ D'Oeste - RO  ┆              ┆          ┆ principal            ┆       │
│ 2022 ┆ 110001           ┆ Alta Floresta ┆ 6803         ┆ agua     ┆ pct_agua_sem_rede_ca ┆ 0.03  │
│      ┆                  ┆ D'Oeste - RO  ┆              ┆          ┆ rro_pipa             ┆       │
│ 2022 ┆ 110001           ┆ Alta Floresta ┆ 6803         ┆ agua     ┆ pct_agua_sem_rede_ch ┆ 0.04  │
│      ┆                  ┆ D'Oeste - RO  ┆              ┆          ┆ uva                  ┆       │
└──────┴──────────────────┴───────────────┴──────────────┴──────────┴──────────────────────┴───────┘